import turtle

turtle.backward(50)
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(30)
turtle.penup()
turtle.backward(30)
turtle.pendown()
turtle.left(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)

#F
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.backward(50)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.backward(50)
turtle.pendown()
turtle.right(90)
turtle.forward(70)

turtle.exitonclick()